# Generated by Django 5.2.6 on 2025-11-14 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categoria_conteudo',
            },
        ),
        migrations.CreateModel(
            name='conteudoTrilha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('url_video', models.URLField(max_length=500)),
                ('descricao', models.TextField(help_text='Resumo sobre o que o vídeo ensina.')),
                ('tags_problema', models.JSONField(default=list, help_text="Lista de 'dores' que este vídeo resolve. Ex: ['conflito', 'procrastinação']")),
                ('dica_rapida', models.TextField(blank=True, help_text="1-2 frases acionáveis que a IA pode usar como 'mini-dica'.")),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteudos', to='api.categoriaconteudo')),
            ],
            options={
                'db_table': 'conteudo_trilha',
            },
        ),
    ]
