# Generated by Django 5.2.6 on 2025-11-20 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_date_joined'),
        ('api', '0002_ticket_ticketmensagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aprimoramentoPessoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empresa')),
            ],
            options={
                'verbose_name_plural': 'Aprimoramento pessoal usuario',
                'db_table': 'aprimoramentoPessoal',
                'ordering': ['-created_at'],
            },
        ),
    ]
