# Generated by Django 5.2.6 on 2025-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aprimoramentopessoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprimoramentopessoal',
            name='resultado',
            field=models.TextField(),
        ),
    ]
