# Generated by Django 5.2.6 on 2025-09-28 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dias_ativos', models.SmallIntegerField(db_column='dias ativos')),
                ('tempo_gasto', models.SmallIntegerField(blank=True, db_column='tempo gasto', null=True)),
                ('comentarios_publicados', models.SmallIntegerField(blank=True, null=True)),
                ('comentarios_respondidos', models.SmallIntegerField(blank=True, null=True)),
                ('interacoes_no_forum', models.SmallIntegerField(blank=True, null=True)),
                ('acessos_semanais', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estatisticas',
            },
        ),
        migrations.CreateModel(
            name='Formulario1',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resposta_ia', models.CharField(max_length=100)),
                ('ticket', models.TextField()),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('chamada', models.TextField()),
                ('telefone', models.TextField()),
                ('regiao', models.TextField(blank=True, db_column='regio', null=True)),
            ],
            options={
                'db_table': 'formulario1',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='senha', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.TextField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('empresa', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('rh', 'Rh'), ('user', 'User')], default='user', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pergunta', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('resposta_a', models.ForeignKey(blank=True, db_column='resposta_a', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.comentarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.posts')),
            ],
            options={
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.posts')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respostas',
                'managed': True,
            },
        ),
    ]
