# Generated by Django 5.2.6 on 2025-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_login',
            field=models.BooleanField(default=True),
        ),
    ]
