# Generated by Django 5.2.6 on 2025-10-16 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenteAprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_empresa', models.CharField(max_length=20, unique=True)),
                ('plano', models.CharField(max_length=50)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20)),
            ],
            options={
                'db_table': 'pendenteAprovado',
            },
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
