# Generated by Django 5.2.6 on 2025-10-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_alter_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_cnpj', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.empresa'),
        ),
    ]
