# Generated by Django 5.2.6 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_primeiro_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='area',
            field=models.CharField(default='Não informada', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lead',
            field=models.IntegerField(default=0),
        ),
    ]
