# Generated by Django 5.2.6 on 2025-11-14 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_area_empresa_is_active_empresa_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_trilha', models.CharField(max_length=255)),
                ('conversa_completa', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_chatbot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnosticos_chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
