# Generated by Django 5.2.6 on 2025-11-21 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='resposta_a',
            field=models.ForeignKey(blank=True, db_column='resposta_a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='accounts.comentarios'),
        ),
    ]
